### ISSUE TITLE
平均池化

### ISSUE THREAD

**Issue by chenyun-cy** [DingXiaoH/DiverseBranchBlock#21]
您好，DBB模块中有一分支是平均池化，那数据下采样尺度变小了，怎么和1*1和k*k的卷积加到一起呢？

**Comment by DingXiaoH** [comment]
avg pool 可以设stride=1 那实际上就变成smoothing了



***@***.***
 
发件人： chenyun-cy
发送时间： 2021-08-16 13:14
收件人： DingXiaoH/DiverseBranchBlock
抄送： Subscribed
主题： [DingXiaoH/DiverseBranchBlock] 平均池化 (#21)
您好，DBB模块中有一分支是平均池化，那数据下采样尺度变小了，怎么和11和kk的卷积加到一起呢？
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenyun-cy** [comment]
十分感谢您，理解了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DingXiaoH/DiverseBranchBlock"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 中午1:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DingXiaoH/DiverseBranchBlock] 平均池化 (#21)





 avg pool 可以设stride=1 那实际上就变成smoothing了 
 
 
 
 ***@***.*** 
   
 发件人： chenyun-cy 
 发送时间： 2021-08-16 13:14 
 收件人： DingXiaoH/DiverseBranchBlock 
 抄送： Subscribed 
 主题： [DingXiaoH/DiverseBranchBlock] 平均池化 (#21) 
 您好，DBB模块中有一分支是平均池化，那数据下采样尺度变小了，怎么和11和kk的卷积加到一起呢？ 
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
